# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revund < Formula
  desc "Review you can trust. AI code review for TypeScript teams."
  homepage "https://revund.dev"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/revund-dev/revund-cli/releases/download/v0.1.4/revund_0.1.4_darwin_amd64.tar.gz"
      sha256 "d14fa4ddfc7aabee30d7f8f07cb5ad348d9062d2fc2e0553a285a10a9d99e718"

      define_method(:install) do
        bin.install "revund"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/revund-dev/revund-cli/releases/download/v0.1.4/revund_0.1.4_darwin_arm64.tar.gz"
      sha256 "9ae098f506543f5ae81ca3019f62b9cd580d8fa1dc144942d252e25e3023b2a8"

      define_method(:install) do
        bin.install "revund"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/revund-dev/revund-cli/releases/download/v0.1.4/revund_0.1.4_linux_amd64.tar.gz"
      sha256 "e3b04f237deca1d0b6440229f23a7f9441de2a40d7c617b0705be306d8d0a415"
      define_method(:install) do
        bin.install "revund"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/revund-dev/revund-cli/releases/download/v0.1.4/revund_0.1.4_linux_arm64.tar.gz"
      sha256 "c0e3e1d026ea14825791e4b5f9daacfe3aeb9501466979e1b92c064967b64e43"
      define_method(:install) do
        bin.install "revund"
      end
    end
  end

  test do
    system "#{bin}/revund --version"
  end
end
