# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revund < Formula
  desc "Review you can trust. AI code review for TypeScript teams."
  homepage "https://revund.dev"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/revund-dev/revund-cli/releases/download/v0.1.1/revund_0.1.1_darwin_amd64.tar.gz"
      sha256 "cd9d6fefe4ce514100065fb6e0fae23ab6b82b5821e1284354fa31b50b2add40"

      define_method(:install) do
        bin.install "revund"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/revund-dev/revund-cli/releases/download/v0.1.1/revund_0.1.1_darwin_arm64.tar.gz"
      sha256 "6d435a8f7a1a97d5334018f3b8981b73928fcabe036e379a58ce94e7e8f4ae21"

      define_method(:install) do
        bin.install "revund"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/revund-dev/revund-cli/releases/download/v0.1.1/revund_0.1.1_linux_amd64.tar.gz"
      sha256 "1f3d5edc1e469d323e9a2f39e932ddf050cba023a8212d28cdc8713260f36a17"
      define_method(:install) do
        bin.install "revund"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/revund-dev/revund-cli/releases/download/v0.1.1/revund_0.1.1_linux_arm64.tar.gz"
      sha256 "565ac5959ff5496b2d638d95a27a47a10b46a5938f75e113d523f71d7b99f2b6"
      define_method(:install) do
        bin.install "revund"
      end
    end
  end

  test do
    system "#{bin}/revund --version"
  end
end
